### ISSUE TITLE
Database locked

### ISSUE THREAD

**Issue by abulte** [namezys/mac_photos#1]
Hi,

Seems like a nice tool, thanks for sharing!

When I execute `create_albumdata.py` I get a "database locked" error, any idea how to avoid this (Photos app is closed)?

Thanks.

**Comment by namezys** [comment]
hello.

I have special options like —tmp-db (I can’t see code now). In this case db copy to tmp file and can be open. But some last changes may be not visible unless Photos sync db to file (usual about some minutes).

**Comment by abulte** [comment]
`--tmp-db` works great , thanks!
